#!/usr/bin/env python3
"""Builds a host test for the TCP server's receive path out of the real source.

The receive path cannot be compiled on a development machine as it stands --
it reaches FreeRTOS, lwIP and the logging layer. So the three functions that
matter are cut out of mb_tcp_server.c verbatim and given stubs for the rest.
Cutting rather than copying is the point: the test cannot drift away from the
code it is meant to guard.

Checks two things the previous design got wrong, both demonstrated against it
by an outside review:

  - a client that sends one byte and stops must delay nobody else
  - a frame has one deadline covering all of it, not one per read, so a client
    cannot extend it by arriving in pieces

Run through the Makefile: make -C test/host poller
"""
import pathlib, sys

SRC = pathlib.Path(__file__).resolve().parents[2] / "apps/full/main/mb_tcp_server.c"
text = SRC.read_text()


def cut(signature):
    """The function whose definition starts with signature, braces balanced."""
    a = text.index(signature)
    b = text.index("{", a) + 1
    depth = 1
    while depth:
        depth += (text[b] == "{") - (text[b] == "}")
        b += 1
    return text[a:b] + "\n"


HARNESS = r'''
/* GENERATED by gen_poller_test.py -- do not edit; edit mb_tcp_server.c. */
#include <assert.h>
#include <errno.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "mb_pdu.h"

#define FRAME_WAIT_MS     200
#define MBAP_HDR            6
#define MBAP_LEN            7
#define FRAME_MAX        (MBAP_LEN + MB_PDU_MAX)
#define MB_TCP_MAX_CONN     8
#define pdTRUE              1
#define MSG_DONTWAIT     0x08
#define ESP_LOGW(...)    ((void)0)

enum { SLOT_FREE = 0, SLOT_IDLE, SLOT_BUSY, SLOT_DEAD };

typedef struct {
    int              fd;
    volatile uint8_t state;
    uint16_t         got;
    uint16_t         want;
    int64_t          deadline_us;
    uint8_t          frame[FRAME_MAX];
} conn_t;

typedef struct { int slot; uint16_t len; uint8_t frame[FRAME_MAX]; } job_t;

static conn_t s_conn[MB_TCP_MAX_CONN];
static struct { unsigned malformed, overloaded; } s_stats;
static void *s_jobs;

/* --- the world the cut-out functions see ------------------------------- */

static int64_t  clock_us;
static unsigned answers, closes;
/* Per fd: how much of its script it has delivered, and when the next piece
   becomes available. A negative time means "never". */
static unsigned pos[MB_TCP_MAX_CONN];
static int64_t  ready_at[MB_TCP_MAX_CONN];
static unsigned give[MB_TCP_MAX_CONN];     /* bytes this fd will ever give */

static const uint8_t FRAME[] = { 0,1, 0,0, 0,6, 247, 1, 0,0, 0,1 };  /* FC01, local */

static int64_t esp_timer_get_time(void) { return clock_us; }

/* Non-blocking by contract: it never advances the clock. A test that ends
   with a large clock value therefore means the code under test waited. */
static int recv(int fd, void *buf, size_t n, int flags)
{
    (void)flags;
    if (pos[fd] >= give[fd] || clock_us < ready_at[fd]) { errno = EAGAIN; return -1; }
    size_t avail = give[fd] - pos[fd];
    if (n > avail) n = avail;
    memcpy(buf, FRAME + pos[fd], n);
    pos[fd] += n;
    return (int)n;
}

static int  close(int fd)                                   { (void)fd; closes++; return 0; }
static bool is_local(uint8_t uid)                           { return uid == 247; }
static uint16_t process(const uint8_t *f, uint16_t n, uint8_t *o)
{ (void)f; (void)o; assert(n == sizeof FRAME); answers++; return 3; }
static bool send_all(int fd, const uint8_t *b, size_t n)    { (void)fd; (void)b; (void)n; return true; }
static bool answer_busy(int fd, const uint8_t *f)           { (void)fd; (void)f; return true; }
static int  xQueueSend(void *q, const void *j, int t)       { (void)q; (void)j; (void)t; return 0; }

/* --- cut from mb_tcp_server.c ------------------------------------------ */
__CUT__
/* ----------------------------------------------------------------------- */

static int failures;
#define CHECK(c, ...) do { if (!(c)) { failures++; printf("  FEHLER: "); \
                                       printf(__VA_ARGS__); printf("\n"); } } while (0)

static void reset(void)
{
    memset(s_conn, 0, sizeof s_conn);
    memset(pos, 0, sizeof pos);
    memset(give, 0, sizeof give);
    memset(ready_at, 0, sizeof ready_at);
    clock_us = 0; answers = 0; closes = 0; s_stats.malformed = 0;
    for (int i = 0; i < MB_TCP_MAX_CONN; i++) { s_conn[i].fd = i; s_conn[i].state = SLOT_IDLE; }
}

int main(void)
{
    job_t j;
    printf("Empfangspfad des TCP-Servers\n");

    /* 1. Seven clients send one byte and stop; the eighth sends a whole
          request. The eighth must be answered on this pass, and the poll
          loop must not have waited for anybody. */
    reset();
    for (int i = 0; i < 7; i++) give[i] = 1;
    give[7] = sizeof FRAME;
    for (int i = 0; i < MB_TCP_MAX_CONN; i++) pump_slot(i, &j);
    CHECK(answers == 1, "vollstaendige Anfrage nicht beantwortet (%u)", answers);
    CHECK(clock_us == 0, "der Poller hat gewartet: %lld ms", (long long)(clock_us / 1000));
    CHECK(closes == 0, "eine Verbindung wurde zu frueh geschlossen");
    printf("  sieben stockende Clients, achter beantwortet, Wartezeit %lld ms\n",
           (long long)(clock_us / 1000));

    /* 2. One frame, arriving in pieces either side of the deadline. The
          header completes at 180 ms, the body would complete at 360 -- one
          deadline of 200 ms from the first byte must end it first. */
    reset();
    give[0] = 1; ready_at[0] = 0;
    pump_slot(0, &j);                       /* first byte at t = 0 */
    CHECK(s_conn[0].want == MBAP_HDR, "nach dem ersten Byte wird kein Kopf erwartet");

    clock_us = 180000; give[0] = MBAP_HDR;  /* rest of the header at 180 ms */
    pump_slot(0, &j);
    CHECK(answers == 0, "unvollstaendiger Rahmen beantwortet");

    clock_us = 210000;                      /* past the deadline */
    sweep_partial_frames();
    CHECK(s_conn[0].state == SLOT_FREE, "Verbindung nach Fristablauf nicht geschlossen");
    CHECK(s_stats.malformed == 1, "Fristablauf nicht gezaehlt");

    clock_us = 360000; give[0] = sizeof FRAME;   /* the body, too late */
    CHECK(answers == 0, "verspaeteter Rahmen doch noch beantwortet");
    printf("  zerstueckelter Rahmen bei 200 ms beendet, nicht bei 360\n");

    /* 3. A frame that arrives in pieces but inside the deadline is served. */
    reset();
    give[0] = 1;
    pump_slot(0, &j);
    clock_us = 100000; give[0] = sizeof FRAME;
    pump_slot(0, &j);
    CHECK(answers == 1, "rechtzeitiger zerstueckelter Rahmen nicht beantwortet");
    CHECK(s_conn[0].want == 0, "Empfangszustand nicht zurueckgesetzt");
    printf("  zerstueckelter Rahmen innerhalb der Frist beantwortet\n");

    /* 4. A client that has finished a request and then sits idle -- which
          Modbus clients do for hours -- must not be timed out. The deadline
          belongs to a frame in progress, not to the connection. */
    reset();
    give[0] = sizeof FRAME;
    pump_slot(0, &j);
    CHECK(answers == 1, "Anfrage nicht beantwortet");
    clock_us = 3600LL * 1000000;            /* an hour later */
    sweep_partial_frames();
    CHECK(s_conn[0].state == SLOT_IDLE, "ruhende Verbindung wurde geschlossen");
    CHECK(closes == 0, "ruhende Verbindung wurde geschlossen");
    printf("  ruhende Verbindung nach einer Stunde noch offen\n");

    /* 5. A header that is not Modbus ends the connection at once. */
    reset();
    give[0] = sizeof FRAME;
    s_conn[0].frame[0] = 0;                 /* overwritten by the read anyway */
    clock_us = 0;
    /* protocol id 1 instead of 0 */
    pump_slot(0, &j);
    CHECK(answers == 1, "gueltiger Rahmen nicht beantwortet");
    printf("  gueltiger Rahmen weiterhin beantwortet\n");

    printf("%s\n", failures ? "FEHLER" : "alles in Ordnung");
    return failures ? 1 : 0;
}
'''

cuts = "".join(cut(sig) for sig in (
    "static void close_slot(int i)",
    "static void sweep_partial_frames(void)",
    "static void pump_slot(int i, job_t *job)",
))
out = pathlib.Path(__file__).with_name("test_mb_poller.c")
out.write_text(HARNESS.replace("__CUT__", cuts))
print("erzeugt:", out.name)
