#pragma once

// Auto-embed of dsl.js — keep in sync with dsl.js (canonical source).
static const char DSL_JS_SOURCE[] =
"'use strict';\n"
"var _rules = [];\n"
"\n"
"function MqttCondition(topic) {\n"
"    this.topic = topic;\n"
"    this._predicate = null;\n"
"    this.value = null;\n"
"    this._seen = false;\n"
"}\n"
"MqttCondition.prototype.is = function(predicate) {\n"
"    this._predicate = predicate;\n"
"    return this;\n"
"};\n"
"MqttCondition.prototype._check = function() {\n"
"    if (!this._seen) return false;\n"
"    if (!this._predicate) return true;\n"
"    return !!this._predicate(this.value);\n"
"};\n"
"\n"
"function InputCondition(ch) {\n"
"    this.channel = ch;\n"
"    this._expected = undefined;\n"
"}\n"
"InputCondition.prototype.is = function(expected) {\n"
"    this._expected = expected;\n"
"    return this;\n"
"};\n"
"InputCondition.prototype._check = function() {\n"
"    var cur = _di_get(this.channel);\n"
"    if (this._expected === undefined) return true;\n"
"    return cur === this._expected;\n"
"};\n"
"\n"
"function mqtt(topic)  { return new MqttCondition(topic); }\n"
"function input(ch)    { return new InputCondition(ch); }\n"
"function output(ch) {\n"
"    return {\n"
"        set: function(v)  { _dout_set(ch, !!v); },\n"
"        get: function()   { return _dout_get(ch); }\n"
"    };\n"
"}\n"
"\n"
"function RuleBuilder(name) {\n"
"    this.name = name;\n"
"    this._conditions = [];\n"
"}\n"
"RuleBuilder.prototype.when = function() {\n"
"    for (var i = 0; i < arguments.length; i++)\n"
"        this._conditions.push(arguments[i]);\n"
"    return this;\n"
"};\n"
"RuleBuilder.prototype.then = function(action) {\n"
"    _rules.push({ name: this.name, conditions: this._conditions, action: action });\n"
"};\n"
"function rule(name) { return new RuleBuilder(name); }\n"
"\n"
"function _on_mqtt(topic, payload) {\n"
"    for (var i = 0; i < _rules.length; i++) {\n"
"        var conds = _rules[i].conditions;\n"
"        for (var j = 0; j < conds.length; j++) {\n"
"            var c = conds[j];\n"
"            if (c instanceof MqttCondition && c.topic === topic) {\n"
"                c.value = payload;\n"
"                c._seen = true;\n"
"            }\n"
"        }\n"
"    }\n"
"    _fire_matching();\n"
"}\n"
"\n"
"function _on_input(channel, state) {\n"
"    _fire_matching();\n"
"}\n"
"\n"
"function _fire_matching() {\n"
"    for (var i = 0; i < _rules.length; i++) {\n"
"        var r = _rules[i];\n"
"        var all_match = true;\n"
"        for (var j = 0; j < r.conditions.length; j++) {\n"
"            if (!r.conditions[j]._check()) { all_match = false; break; }\n"
"        }\n"
"        if (all_match) {\n"
"            try {\n"
"                r.action();\n"
"            } catch (e) {\n"
"                print('[rule:' + r.name + '] error: ' + e);\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"
;
